import Head from 'next/head'
import Page from "@/components/Page";
import InfoBox from "@/components/InfoBox";
import TextBox from "@/components/TextBox";
import {ourWorks} from "@/api/ourWorksApi";
import React from "react";

export default function Home({works}:any) {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main>
                <Page
                    title="CASE STUDIES"
                    description="Our work speaks for itself so please browse some of our proudest achievements."
                    works={works}
                />
                <InfoBox data={[
                    {title: 'CLIENT:', text: 'Financial Agent LTD'},
                    {title: 'CASE LAUNCH:', text: 'September 2022'},
                    {title: 'WEBSITE:', text: 'www.financialagent.co.uk'}
                ]}/>
                <TextBox/>

            </main>
        </>
    )
}

export async function getStaticProps() {
    try {
        let {works, total} = await ourWorks();
        return {
            props: {
                works,
                total
            },
        }
    } catch (e) {}

    return {
        props: {
            works: [],
            total: 0
        },
    }
}